---
- name: add docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker
  dnf:
    name: docker-ce-3:18.09.1-3.el7
    state: present
    update_cache: yes
    skip_broken: yes

- name: Install docker-compose
  pip:
    name: docker-compose
    executable: pip3

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: create docker-compose directory
  file:
    dest: "{{ docker_compose_dir }}"
    state: directory

