---

- name: set default way to install docker
  set_fact:
    docker_install: package

- name: set variable to install docker using dnf from external repo
  set_fact:
    docker_install: dnf_repo
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"

- name: add external docker rpm repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: docker_install == "dnf_repo"

- name: install docker form external repo using dnf
  dnf:
    name: docker-ce-3:18.09.1-3.el7
    state: present
    update_cache: yes
    skip_broken: yes
  when: docker_install == "dnf_repo"

- name: install docker using package module
  package:
    name: docker
    state: present
  when: docker_install == "package"

- name: Install docker-compose
  pip:
    name: docker-compose
    executable: pip3

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: create docker-compose directory
  file:
    dest: "{{ docker_compose_dir }}"
    state: directory

