version: '3'
services:
  jenkins:
  image: jenkins:2.60.3
  ports:
    - 8080:8080
    - 50000:50000
  volumes:
    - type: bind
      source: /var/jenkins
      target: /var/jenkins_home
  restart: always

